name: "PR 자동 라벨링"

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: PR 라벨 자동 부착
        uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
